# Welcome to Serverless!

service: apportion-bankfeed # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: "ap-southeast-2"

functions:
  bankStatement:
    handler: handler.endpoint
    events:
      - http:
          path: bankstatement
          method: get
